# PyTorch

## Tensor operations

1. basic math operations

In [1]:
import torch

In [8]:
torch.tensor([1.0, 2.0, 3.0])

tensor([1., 2., 3.])

In [9]:
torch.ones(3)

tensor([1., 1., 1.])

In [10]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.randn(3, 3)

tensor([[-0.1477, -0.1663,  1.2852],
        [-0.2432,  0.8163,  0.1741],
        [-3.0049, -0.2027,  0.3979]])

In [12]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])
x + y

tensor([5., 7., 9.])

In [13]:
x - y

tensor([-3., -3., -3.])

In [14]:
x * y

tensor([ 4., 10., 18.])

In [15]:
x / y

tensor([0.2500, 0.4000, 0.5000])

In [16]:
x * 2

tensor([2., 4., 6.])

In [17]:
x + 2

tensor([3., 4., 5.])

In [18]:
x ** 2

tensor([1., 4., 9.])

In pytorch using method with '_' means that the operation is in place

In [19]:
print(y)
y.add_(x)
print(y)

tensor([4., 5., 6.])
tensor([5., 7., 9.])


2. Slicing operations

In [24]:
x = torch.randn(3, 3)
print(x)
print(x[:, 0]) # returns the first column
print(x[0, :]) # returns the first row
print(x[0, 1]) # returns the element at the first row and second column

tensor([[ 0.6720,  1.6719,  1.5661],
        [-1.5738, -1.3012, -0.1662],
        [ 0.0767,  1.4851,  0.5772]])
tensor([ 0.6720, -1.5738,  0.0767])
tensor([0.6720, 1.6719, 1.5661])
tensor(1.6719)


3. Reshaping operations

In [26]:
y = x.view(9)
y

tensor([ 0.6720,  1.6719,  1.5661, -1.5738, -1.3012, -0.1662,  0.0767,  1.4851,
         0.5772])

In [28]:
z = x.view(-1)
z

tensor([ 0.6720,  1.6719,  1.5661, -1.5738, -1.3012, -0.1662,  0.0767,  1.4851,
         0.5772])

4. using numpy array

In [32]:
import numpy as np

In [29]:
a = torch.ones(5)
b = a.numpy()
type(b)

numpy.ndarray

In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


As you saw `a` and `b` share the same memory location (if the tensor is on `cpu`)

In [34]:
a = np.ones(5)
b = torch.from_numpy(a)
type(b)

torch.Tensor

In [35]:
b.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


As you saw `a` and `b` share the same memory location (even in the case of going from `numpy` to `torch`)

5. using GPU

In [36]:
if torch.cuda.is_available():
    print("CUDA is available")
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
else:
    print("This is a CPU-only machine")

This is a CPU-only machine


As you see in the example above, you can easily move tensors to the GPU by using the `.to` method.
or you can use the `device=torch.device("cuda")` parameter in the tensor constructor